# Generated by Django 5.2.13 on 2026-05-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('voice', 'Voice'), ('rule', 'Rule'), ('system', 'System')], default='manual', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('completed', 'Completed')], default='queued', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['command_id'], name='control_com_command_f5000c_idx'), models.Index(fields=['target'], name='control_com_target_2f3525_idx'), models.Index(fields=['status', '-created_at'], name='control_com_status_13666e_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutputTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=50)),
                ('current_state', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='control_out_key_e97bc9_idx'), models.Index(fields=['kind'], name='control_out_kind_64e10a_idx')],
            },
        ),
    ]
